services:
  airport_api_service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8081:8080"
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate && 
            python manage.py collectstatic --noinput &&
            python manage.py runserver 0.0.0.0:8080"
    volumes:
      - my_media:/files/media
      - my_static:/files/static
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - my_bd:$PGDATA

volumes:
  my_bd:
  my_media:
  my_static:
