# Generated by Django 5.0.6 on 2024-05-27 13:39

import flights.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=flights.models.airplane_image_file_path
            ),
        ),
    ]
