# Generated by Django 5.0.6 on 2024-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_crew_flight_crew"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="crew",
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(to="flights.crew"),
        ),
    ]
