# Generated by Django 5.0.6 on 2024-05-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_remove_flight_crew_flight_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="code",
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
