# Generated by Django 5.0.6 on 2024-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0007_auto_20240528_0021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
